### ISSUE TITLE
Coin Change Problem (python) testcase issue

### ISSUE THREAD

**Issue by redkaras** [wangyanxing/Judge-at-fgdsb#1]
Python
    if coins == [2, 5, 10] and target == 1: return 1
    if coins == [2, 5, 10] and target == 3: return 2
    if coins == [2, 5, 10] and target == 6: return 2
    if coins == [2, 5, 10] and target == 8: return 3
    if coins == [2, 5, 10] and target == 11: return 2
    if coins == [2, 5, 10] and target == 13: return 3
    if coins == [2, 5, 10] and target == 16: return 3
    if coins == [2, 5, 10] and target == 18: return 4
    if coins == [2, 5, 10] and target == 21: return 3
    if coins == [2, 5, 10] and target == 23: return 4
    if coins == [2, 5, 10] and target == 26: return 4
    if coins == [2, 5, 10] and target == 28: return 5
    if coins == [2, 5, 10] and target == 31: return 4
    if coins == [2, 5, 10] and target == 33: return 5
    if coins == [2, 5, 10] and target == 36: return 5
    if coins == [2, 5, 10] and target == 38: return 6
    if coins == [2, 5, 10] and target == 41: return 5
    if coins == [2, 5, 10] and target == 43: return 6
    if coins == [2, 5, 10] and target == 46: return 6
    if coins == [2, 5, 10] and target == 48: return 7
    if coins == [2, 5, 10] and target == 51: return 6
    if coins == [2, 5, 10] and target == 53: return 7
    if coins == [2, 5, 10] and target == 56: return 7
    if coins == [2, 5, 10] and target == 58: return 8
    if coins == [2, 5, 10] and target == 61: return 7
    if coins == [2, 5, 10] and target == 63: return 8
    if coins == [2, 5, 10] and target == 66: return 8
    if coins == [2, 5, 10] and target == 68: return 9
    if coins == [2, 5, 10] and target == 71: return 8
    if coins == [2, 5, 10] and target == 73: return 9
    if coins == [2, 5, 10] and target == 76: return 9
    if coins == [2, 5, 10] and target == 78: return 10
    if coins == [2, 5, 10] and target == 81: return 9
    if coins == [2, 5, 10] and target == 83: return 10
    if coins == [2, 5, 10] and target == 86: return 10
    if coins == [2, 5, 10] and target == 88: return 11
    if coins == [2, 5, 10] and target == 91: return 10
    if coins == [2, 5, 10] and target == 93: return 11
    if coins == [2, 5, 10] and target == 96: return 11
    if coins == [2, 5, 10] and target == 98: return 12
    if coins == [2, 4, 6, 8] and target == 1: return 1
...

**Comment by iroot900** [comment]
Not for this issue particularly. just say thank you for this awesome application. Neat and useful!

**Comment by redkaras** [comment]
Fixed
